### ISSUE TITLE
Validator/Editor. Error on Load "Github says 'unauthorized".

### ISSUE THREAD

**Issue by JohnLukeBentley** [Juris-M/juris-m.github.io#99]
To reproduce:

* Goto https://juris-m.github.io/editor/
* Source: Jurisdiction Module
* Type "Laputa".
* Click on [Load]
* Observe ...

> Error
> Unable to get your user account details for some reason.
> GitHub says
> "Unauthorized"

This has occurred all of a sudden. I've previously been able to use the editor with success.

I'm logged into Github. 

I tried clearing everything in my browser (Ctrl + Shift + Del), ticking everything (cache, cookies, etc); restarting firefox, and signing in again to github. That sign was successful but the above JurisM editor error was not solved.

**Comment by fbennett** [comment]
That's not good. I'll check my access after dinner here. The site needs a
logout method. Important for other reasons, but that would probably also
clear the login keys to re-establish a working connection.

**Comment by fbennett** [comment]
Oh - I have another report that the gateway server is down. Will check
after dinner.

**Comment by JohnLukeBentley** [comment]
That makes sense. Sounds like a mere matter of waiting for the gateway server (wherever that is, and whomever controls it) to come back online. 

Perhaps you could test for this condition and provide a more informative error message. Something like

> Github's (?) Gateway Server is temporarily down. You'll not be able to validate during this time

**Comment by fbennett** [comment]
Should be back up now. The server got fussy about the syntax of a setting that was previously fine. Someone must have tweaked something in the VM. Back up and running.

**Comment by JohnLukeBentley** [comment]
Thanks. (I can confirm) working at my end now too.
